/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bubble: typeof import('./../components/messages/Bubble.vue')['default']
    Card: typeof import('./../components/messages/Card.vue')['default']
    ContactRow: typeof import('./../components/ContactRow.vue')['default']
    ContextMenu: typeof import('./../components/ContextMenu.vue')['default']
    Emoji: typeof import('./../components/chats/Emoji.vue')['default']
    File: typeof import('./../components/messages/File.vue')['default']
    Forward: typeof import('./../components/messages/Forward.vue')['default']
    Forwarder: typeof import('./../components/chats/Forwarder.vue')['default']
    Image: typeof import('./../components/messages/Image.vue')['default']
    Input: typeof import('./../components/chats/Input.vue')['default']
    Lottie: typeof import('./../components/Lottie.vue')['default']
    Markdown: typeof import('./../components/messages/Markdown.vue')['default']
    Media: typeof import('./../components/messages/Media.vue')['default']
    Profile: typeof import('./../components/chats/Profile.vue')['default']
    Quote: typeof import('./../components/messages/Quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../components/chats/Select.vue')['default']
    SessionRow: typeof import('./../components/SessionRow.vue')['default']
    Stream: typeof import('./../components/chats/Stream.vue')['default']
    System: typeof import('./../components/messages/System.vue')['default']
    Text: typeof import('./../components/messages/Text.vue')['default']
    Tools: typeof import('./../components/chats/Tools.vue')['default']
  }
}
